import phoneImg from "@/assets/phone.png";
import notebookImg from "@/assets/notebook.png";
import laptopImg from "@/assets/laptop.png";
import { IProduct } from "@/types/types";

const ProductGradeCard: IProduct[] = [
  {
    id: 1,
    type: "Smartphone",
    title: "Apple iPhone 13 Pro Max 256 ГБ серый",
    brand: "Apple",
    img: phoneImg,
    characteristics: {
      design: 4,
      battery: 2,
      display: 4,
      camera: 5,
      answer: 5,
      portability: 4,
      ram: 4,
      gbInbuilt: 128,
      memoryCard: false,
      mAhBattery: 3240,
      FastCharging: true,
      OC: "IOS v15",
    },
    price: "114 099",
  },
  {
    id: 2,
    type: "Smartphone",
    title: "Apple iPhone 15 Pro Max 126 ГБ черный",
    brand: "Apple",
    img: phoneImg,
    characteristics: {
      design: 3,
      battery: 1,
      display: 5,
      camera: 4,
      answer: 2,
      portability: 3,
      ram: 4,
      gbInbuilt: 256,
      memoryCard: false,
      mAhBattery: 3240,
      FastCharging: true,
      OC: "IOS v15",
    },
    price: "120 099",
  },
  {
    id: 3,
    type: "Smartphone",
    title: "Apple iPhone 10 Pro Max 256 ГБ белый",
    brand: "Apple",
    img: phoneImg,
    characteristics: {
      design: 1,
      battery: 2,
      display: 3,
      camera: 1,
      answer: 2,
      portability: 3,
      ram: 4,
      gbInbuilt: 512,
      memoryCard: false,
      mAhBattery: 3240,
      FastCharging: true,
      OC: "IOS v15",
    },
    price: "105 099",
  },
  {
    id: 4,
    type: "Tablet",
    title: "IPad",
    brand: "Apple",
    img: laptopImg,
    characteristics: {
      design: 1,
      battery: 2,
      display: 2,
      camera: 5,
      answer: 5,
      portability: 3,
      ram: 8,
      gbInbuilt: 512,
      memoryCard: false,
      mAhBattery: 2840,
      FastCharging: false,
      OC: "IOS v16",
    },
    price: "90 199",
  },
  {
    id: 5,
    type: "Notebook",
    title: "MSI Ноутбук RTX 4060 Intel Core I9",
    brand: "Msi",
    img: notebookImg,
    characteristics: {
      design: 4,
      battery: 2,
      display: 4,
      camera: 5,
      answer: 5,
      portability: 4,
      ram: 4,
      gbInbuilt: 128,
      memoryCard: false,
      mAhBattery: 3240,
      FastCharging: true,
      OC: "Windows 11",
    },
    price: "154 000",
  },
  {
    id: 6,
    type: "Smartphone",
    title: "Google Pixel",
    brand: "Google",
    img: phoneImg,
    characteristics: {
      design: 1,
      battery: 2,
      display: 3,
      camera: 1,
      answer: 2,
      portability: 3,
      ram: 4,
      gbInbuilt: 512,
      memoryCard: false,
      mAhBattery: 3240,
      FastCharging: true,
      OC: "IOS v15",
    },
    price: "170 099",
  },
  {
    id: 7,
    type: "Smartphone",
    title: "Lenovo",
    brand: "Lenovo",
    img: phoneImg,
    characteristics: {
      design: 1,
      battery: 2,
      display: 3,
      camera: 1,
      answer: 2,
      portability: 3,
      ram: 4,
      gbInbuilt: 512,
      memoryCard: false,
      mAhBattery: 3240,
      FastCharging: true,
      OC: "IOS v15",
    },
    price: "105 099",
  },
  {
    id: 8,
    type: "Notebook",
    title: "Acer Ноутбук RTX 4060 Intel Core I9",
    brand: "Acer",
    img: notebookImg,
    characteristics: {
      design: 4,
      battery: 2,
      display: 4,
      camera: 5,
      answer: 5,
      portability: 4,
      ram: 4,
      gbInbuilt: 128,
      memoryCard: false,
      mAhBattery: 3240,
      FastCharging: true,
      OC: "Windows 11",
    },
    price: "154 000",
  },
  {
    id: 9,
    type: "Tablet",
    title: "Lenovo",
    brand: "Lenovo",
    img: laptopImg,
    characteristics: {
      design: 1,
      battery: 2,
      display: 2,
      camera: 5,
      answer: 5,
      portability: 3,
      ram: 8,
      gbInbuilt: 512,
      memoryCard: false,
      mAhBattery: 2840,
      FastCharging: false,
      OC: "Andriod",
    },
    price: "90 199",
  },
];

export default ProductGradeCard;
